import { writeFileSync } from 'node:fs'
import type { Config } from './config'
import { all, type Db } from './db'
import { JsonRpc } from './l1/rpc'
import { log, sleep } from './log'
import { CHAINS, type ChainId, KNOWN_ADDRESSES } from './protocol'

/**
 * Builds `src/labels.generated.ts`: public labels for the L1 addresses that
 * deposit to or withdraw from Payy. Every label comes from public data and
 * carries its source:
 *
 * - Etherscan's labels, as republished by github.com/dawsbot/eth-labels
 *   (Ethereum) and github.com/brianleect/etherscan-labels (Polygon).
 * - For the addresses that receive the most withdrawals: the name of their
 *   verified contract on Etherscan, and exchange deposit addresses, which
 *   forward what they receive to a labelled exchange wallet.
 *
 * Nothing here names a private person: an address gets a label only if it
 * is a labelled entity, a contract, or forwards to an exchange.
 */

const OUT = 'src/labels.generated.ts'
const DATASETS = [
  {
    url: 'https://raw.githubusercontent.com/dawsbot/eth-labels/v1/data/csv/accounts.csv',
    source: 'Etherscan label (eth-labels)',
    format: 'csv' as const,
  },
  {
    url: 'https://raw.githubusercontent.com/brianleect/etherscan-labels/main/data/etherscan/combined/combinedAllLabels.json',
    source: 'Etherscan label (etherscan-labels, 2023)',
    format: 'json' as const,
    chain: '1',
  },
  {
    url: 'https://raw.githubusercontent.com/brianleect/etherscan-labels/main/data/polygonscan/combined/combinedAllLabels.json',
    source: 'Polygonscan label (etherscan-labels, 2023)',
    format: 'json' as const,
    chain: '137',
  },
]
/** withdrawals or USDC received that make an address worth looking up */
const MIN_WITHDRAWALS = 20
const MIN_RECEIVED = 20_000 * 1e6
/** share of an address's outgoing USDC transfers that must go to one exchange */
const FORWARD_SHARE = 0.8
const EXCHANGES = [
  'binance',
  'coinbase',
  'kraken',
  'okx',
  'bybit',
  'bitget',
  'kucoin',
  'gate-io',
  'huobi',
  'htx',
  'crypto-com',
  'bitfinex',
  'gemini',
  'mexc',
  'bitstamp',
  'upbit',
  'bithumb',
  'bitvavo',
  'exchange',
]
const CHAIN_IDS: Record<ChainId, string> = { ethereum: '1', polygon: '137' }

export interface PublicLabel {
  label: string
  source: string
}

interface Entry {
  name: string
  tags: string[]
  chain: string
  source: string
}

export async function buildLabels(db: Db, config: Config): Promise<void> {
  const active = activeAddresses(db)
  const dataset = await loadDatasets()
  const labels = new Map<string, PublicLabel>()

  for (const [address, chains] of active) {
    if (KNOWN_ADDRESSES[address]) continue
    const entry = pick(dataset.get(address), chains)
    const text = entry && describe(entry)
    if (entry && text)
      labels.set(address, { label: text, source: entry.source })
  }
  log('dataset labels', { labels: labels.size, addresses: active.size })

  if (!config.etherscanKey) {
    log('ETHERSCAN_API_KEY not set: skipping contract and exchange checks')
  } else {
    const etherscan = new Etherscan(config.etherscanKey)
    for (const chain of Object.values(CHAINS)) {
      const url = config.rpcUrls[chain.id]
      if (!url) continue
      const top = significantRecipients(db, chain.id).filter(
        (a) => !labels.has(a) && !KNOWN_ADDRESSES[a],
      )
      log(`${chain.id} checking`, { addresses: top.length })
      const codes = await new JsonRpc(url).getCodes(top)
      for (const [i, address] of top.entries()) {
        if (i % 50 === 49) log(`${chain.id} checked`, { addresses: i + 1 })
        const code = codes.get(address) ?? '0x'
        const found =
          code === '0x'
            ? await forwardsToExchange(etherscan, chain.id, address, dataset)
            : await contractName(etherscan, chain.id, address, code, dataset)
        if (found) labels.set(address, found)
      }
    }
  }

  const sorted = [...labels].sort(([a], [b]) => a.localeCompare(b))
  writeFileSync(
    OUT,
    `// Generated by \`pnpm dev labels\` (src/labels.ts). Do not edit by hand.\n\nexport const PUBLIC_LABELS: Record<string, { label: string; source: string }> = ${JSON.stringify(Object.fromEntries(sorted), null, 2)}\n`,
  )
  log('labels written', { file: OUT, labels: labels.size })
}

/** Every depositor and withdrawal recipient, with the chains it used */
function activeAddresses(db: Db): Map<string, Set<ChainId>> {
  const result = new Map<string, Set<ChainId>>()
  const add = (address: string, chain: ChainId) => {
    const set = result.get(address) ?? new Set()
    set.add(chain)
    result.set(address, set)
  }
  for (const r of all<{ a: string; chain: ChainId }>(
    db,
    'select distinct depositor as a, chain from deposit',
  )) {
    add(r.a, r.chain)
  }
  for (const r of all<{ a: string; chain: ChainId }>(
    db,
    'select distinct recipient as a, chain from burned',
  )) {
    add(r.a, r.chain)
  }
  return result
}

function significantRecipients(db: Db, chain: ChainId): string[] {
  return all<{ a: string }>(
    db,
    `select t.burn_addr as a from txn t
     where t.kind = 3 and exists (
       select 1 from burned b where b.burn_hash = t.msg_hash and b.chain = ?)
     group by t.burn_addr having count(*) >= ? or sum(t.amount) >= ?`,
    chain,
    MIN_WITHDRAWALS,
    MIN_RECEIVED,
  ).map((r) => r.a)
}

async function loadDatasets(): Promise<Map<string, Entry[]>> {
  const result = new Map<string, Entry[]>()
  const add = (address: string, entry: Entry) => {
    const key = address.toLowerCase()
    const list = result.get(key) ?? []
    list.push(entry)
    result.set(key, list)
  }
  for (const d of DATASETS) {
    const res = await fetch(d.url, { signal: AbortSignal.timeout(120_000) })
    if (!res.ok) throw new Error(`${d.url}: ${res.status}`)
    const text = await res.text()
    if (d.format === 'csv') {
      for (const line of text.split('\n').slice(1)) {
        const [address, chain, tag, name] = parseCsvLine(line)
        if (!address || !chain) continue
        add(address, {
          name: name ?? '',
          tags: tag ? [tag] : [],
          chain,
          source: d.source,
        })
      }
    } else {
      const json = JSON.parse(text) as Record<
        string,
        { name: string; labels: string[] }
      >
      for (const [address, v] of Object.entries(json)) {
        add(address, {
          name: v.name,
          tags: v.labels,
          chain: d.chain ?? '1',
          source: d.source,
        })
      }
    }
    log('dataset loaded', { url: d.url })
  }
  return result
}

function parseCsvLine(line: string): string[] {
  const cells: string[] = []
  let cell = ''
  let quoted = false
  for (const ch of line) {
    if (ch === '"') quoted = !quoted
    else if (ch === ',' && !quoted) {
      cells.push(cell)
      cell = ''
    } else cell += ch
  }
  cells.push(cell)
  return cells
}

/** The entry for the chain the address was used on, the newest source first */
function pick(
  entries: Entry[] | undefined,
  chains: Set<ChainId> | ChainId[],
): Entry | undefined {
  const ids = new Set([...chains].map((c) => CHAIN_IDS[c]))
  return entries?.find((e) => ids.has(e.chain) && describe(e))
}

function describe(e: Entry): string | undefined {
  const name = e.name.trim()
  // "Bitget Dep: 0x8b1B…" names an exchange deposit address
  const deposit = name.match(/^(.+?) Dep: 0x[0-9a-fA-F]+$/)
  if (deposit) return `${deposit[1]} deposit`
  if (name && name !== 'null') return name
  const tags = e.tags.filter((t) => t && t !== 'null')
  return tags.length ? tags.join(', ') : undefined
}

function isExchange(e: Entry): boolean {
  return e.tags.some((t) => EXCHANGES.some((x) => t.includes(x)))
}

/** "Coinbase 10" -> "Coinbase", "Bitget Dep: 0x8b1b…" -> "Bitget" */
function exchangeName(e: Entry): string {
  const name = describe(e) ?? ''
  return name.split(/\s+(?:\d|Dep\b|Hot\b|Deposit\b)|:/)[0]?.trim() || name
}

async function forwardsToExchange(
  etherscan: Etherscan,
  chain: ChainId,
  address: string,
  dataset: Map<string, Entry[]>,
): Promise<PublicLabel | undefined> {
  const transfers = await etherscan.get<{ from: string; to: string }[]>(chain, {
    module: 'account',
    action: 'tokentx',
    contractaddress: CHAINS[chain].usdc,
    address,
    page: '1',
    offset: '200',
    sort: 'desc',
  })
  const out = (transfers ?? []).filter((t) => t.from.toLowerCase() === address)
  if (out.length < 3) return undefined
  const counts = new Map<string, number>()
  for (const t of out) {
    const to = t.to.toLowerCase()
    counts.set(to, (counts.get(to) ?? 0) + 1)
  }
  const [target, n] = [...counts].sort((a, b) => b[1] - a[1])[0] ?? []
  if (!target || !n || n / out.length < FORWARD_SHARE) return undefined
  const entry = dataset.get(target)?.find(isExchange)
  if (!entry) return undefined
  return {
    label: `${exchangeName(entry)} deposit`,
    source: `forwards ${n} of its last ${out.length} USDC transfers to ${describe(entry)} (${entry.source})`,
  }
}

async function contractName(
  etherscan: Etherscan,
  chain: ChainId,
  address: string,
  code: string,
  dataset: Map<string, Entry[]>,
): Promise<PublicLabel | undefined> {
  // EIP-7702: an EOA delegating to a contract, `0xef0100 || delegate`
  if (code.startsWith('0xef0100')) {
    const delegate = `0x${code.slice(8, 48)}`
    const entry = pick(dataset.get(delegate), [chain])
    const name = entry
      ? describe(entry)
      : await verifiedName(etherscan, chain, delegate)
    return name
      ? { label: `EIP-7702 account (${name})`, source: 'delegation in code' }
      : undefined
  }
  const name = await verifiedName(etherscan, chain, address)
  return name
    ? { label: name, source: 'verified contract name (Etherscan)' }
    : undefined
}

async function verifiedName(
  etherscan: Etherscan,
  chain: ChainId,
  address: string,
  followProxy = true,
): Promise<string | undefined> {
  const source = await etherscan.get<
    { ContractName: string; Proxy: string; Implementation: string }[]
  >(chain, { module: 'contract', action: 'getsourcecode', address })
  const s = source?.[0]
  // a proxy is named after its implementation, one level deep
  if (followProxy && s?.Proxy === '1' && s.Implementation) {
    const impl = await verifiedName(etherscan, chain, s.Implementation, false)
    if (impl) return impl
  }
  return s?.ContractName || undefined
}

/** Etherscan API v2, paced to the free tier's rate limit */
class Etherscan {
  private last = 0

  constructor(private readonly key: string) {}

  async get<T>(
    chain: ChainId,
    params: Record<string, string>,
  ): Promise<T | undefined> {
    const query = new URLSearchParams({
      chainid: CHAIN_IDS[chain],
      ...params,
      apikey: this.key,
    })
    for (let attempt = 0; attempt < 4; attempt++) {
      const wait = this.last + 250 - Date.now()
      if (wait > 0) await sleep(wait)
      this.last = Date.now()
      let json: { status: string; result: unknown }
      try {
        const res = await fetch(`https://api.etherscan.io/v2/api?${query}`, {
          signal: AbortSignal.timeout(30_000),
        })
        json = (await res.json()) as typeof json
      } catch {
        await sleep(1000 * 2 ** attempt)
        continue
      }
      if (json.status === '1') return json.result as T
      // "No transactions found" and the like are empty answers, not errors
      if (typeof json.result !== 'string' || !/rate limit/i.test(json.result)) {
        return undefined
      }
      await sleep(1000 * 2 ** attempt)
    }
    return undefined
  }
}
