// Generated by `pnpm dev labels` (src/labels.ts). Do not edit by hand.

export const PUBLIC_LABELS: Record<string, { label: string; source: string }> =
  {
    '0x0052117d696865c544b9e3559dc96e7d82f996df': {
      label: 'Cobo deposit',
      source:
        'forwards 32 of its last 32 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0x0f6a0374379b455cfac356fa4017284ceccb2d10': {
      label: 'Kernel',
      source: 'verified contract name (Etherscan)',
    },
    '0x1006a10c106b43bc004f4439786a4d93ced93898': {
      label: 'Cobo deposit',
      source:
        'forwards 15 of its last 15 USDC transfers to Cobo: Custody 5 (Etherscan label (eth-labels))',
    },
    '0x1190bfb56c8cddf91c9ac838ff724c006244541f': {
      label: 'Cobo deposit',
      source:
        'forwards 49 of its last 49 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0x126db3213b309a8d554594e591e614425ccac78e': {
      label: 'rocket-pool',
      source: 'Etherscan label (etherscan-labels, 2023)',
    },
    '0x134cea96016fce908541e22d7a327b0a6dc8e658': {
      label: 'Coins.ph deposit',
      source:
        'forwards 8 of its last 8 USDC transfers to Coins.ph: Hot Wallet (Etherscan label (eth-labels))',
    },
    '0x13e1266c57855fa3deb5c60441567122a86dc581': {
      label: 'EIP-7702 account (MetaMask: EIP-7702 Delegator)',
      source: 'delegation in code',
    },
    '0x1856bd7060102360c82f38df1ca26bdb2ca08820': {
      label: 'EIP-7702 account (UniversalGaslessDelegate)',
      source: 'delegation in code',
    },
    '0x1960035b1a12a661f21661f8e9b368d51dfb14bf': {
      label: 'EIP-7702 account (UniversalGaslessDelegate)',
      source: 'delegation in code',
    },
    '0x1d16274161b9bf6a32102b504f212e5ccda9846d': {
      label: 'EIP-7702 account (Kernel)',
      source: 'delegation in code',
    },
    '0x23679f6d2529678864747ec52599b712b33c9cc9': {
      label: 'EIP-7702 account (Trust Wallet: EIP-7702 Delegator 1)',
      source: 'delegation in code',
    },
    '0x32761cd191a9a1b1c85bdeff88df192977dca888': {
      label: 'TopUpV2',
      source: 'verified contract name (Etherscan)',
    },
    '0x384e667f29f1c5087e5fac9761ce9ac8e67a4eec': {
      label: 'TopUpV2',
      source: 'verified contract name (Etherscan)',
    },
    '0x3b30e8561eb362d915b8128445cd1194078304f8': {
      label: 'EIP-7702 account (Simple7702Account)',
      source: 'delegation in code',
    },
    '0x3c330c7565a2299edc46a4bb703aed7c643e33b9': {
      label: 'Forwarder',
      source: 'verified contract name (Etherscan)',
    },
    '0x3e29d169c2a954ae2f10e59ad46cb40bdef3cf6d': {
      label: 'Cobo deposit',
      source:
        'forwards 23 of its last 23 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0x466fb88b07f7c2b82fce56a1a32df63b4d965861': {
      label: 'Forwarder',
      source: 'verified contract name (Etherscan)',
    },
    '0x48a7bea12a800957113662d27468fd1c9e8d42aa': {
      label: 'EIP-7702 account (EIP7702StatelessDeleGator)',
      source: 'delegation in code',
    },
    '0x4a2729588c82e7328fdccee162925dd95ac69eb6': {
      label: 'EIP-7702 account (Trust Wallet: EIP-7702 Delegator 1)',
      source: 'delegation in code',
    },
    '0x4bdfd3ce7bfb07b75a2a59a8f723910dd7147b9c': {
      label: 'EIP-7702 account (MetaMask: EIP-7702 Delegator)',
      source: 'delegation in code',
    },
    '0x4de23f3f0fb3318287378adbde030cf61714b2f3': {
      label: 'blocked',
      source: 'Etherscan label (eth-labels)',
    },
    '0x4f0bf9f13f2f1a1e54aca304c06c1d2267fe8a88': {
      label: 'CoinbaseSmartWallet',
      source: 'verified contract name (Etherscan)',
    },
    '0x54489e452cebcc011fd2d7d6264bb9c13b4b94f1': {
      label: 'Revolut deposit',
      source:
        'forwards 14 of its last 14 USDC transfers to Revolut: Hot Wallet (Etherscan label (eth-labels))',
    },
    '0x55132e2f1b38efb309b82b97664559696b80c840': {
      label: 'EIP-7702 account (UniversalGaslessDelegate)',
      source: 'delegation in code',
    },
    '0x58984cfb1f05bf16bc0b768cd18b814635f0ae58': {
      label: 'Cobo deposit',
      source:
        'forwards 26 of its last 26 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0x5ca6948e4677ed4abadcf8991ff030e95ea01ebe': {
      label: 'Cobo deposit',
      source:
        'forwards 26 of its last 26 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0x5e250cdd4557bdd90f7fcc5aa1bfede25b6b8639': {
      label: 'Bitget deposit',
      source:
        'forwards 28 of its last 28 USDC transfers to Bitget 6 (Etherscan label (eth-labels))',
    },
    '0x5e399f480813d5b60ecbf8b869d7d4dc9d632913': {
      label: 'Bitget deposit',
      source: 'Etherscan label (eth-labels)',
    },
    '0x679ccc96083daeb4b5f78d087d690f1bed0c8c88': {
      label: 'Cobo deposit',
      source:
        'forwards 20 of its last 20 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0x6b465f334e98b8b443ddded9de27912aaca75290': {
      label: 'Stake.com deposit',
      source:
        'forwards 5 of its last 5 USDC transfers to Stake.com (Etherscan label (eth-labels))',
    },
    '0x6e2b62712ec2a542618de7cb8777a64e96a439b2': {
      label: 'Forwarder',
      source: 'verified contract name (Etherscan)',
    },
    '0x73e7573eb612737775283c6a51ebfdbeb291c1c4': {
      label: 'Bybit deposit',
      source:
        'forwards 6 of its last 6 USDC transfers to Bybit: Opensea User (Etherscan label (eth-labels))',
    },
    '0x752df6c7facc1df7575c1ca6fb50f51165cb5a3b': {
      label: 'Fee Recipient: 0x752d...a3b',
      source: 'Etherscan label (eth-labels)',
    },
    '0x7bec2c890f9a6158c15f27f315bd7d5bc0956f05': {
      label: 'Cobo deposit',
      source:
        'forwards 30 of its last 30 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0x84efeb0d7045a93f678fcda4471f205ef6d2361d': {
      label: 'Nexo deposit',
      source:
        'forwards 19 of its last 19 USDC transfers to Nexo 49 (Etherscan label (eth-labels))',
    },
    '0x8ad546865b051e36b0f214144e78f84728edc589': {
      label: 'CEX.IO deposit',
      source:
        'forwards 10 of its last 10 USDC transfers to CEX.IO (Etherscan label (eth-labels))',
    },
    '0x8b1b0880f62fddee9a3d812d94cfb66f1422542b': {
      label: 'Bitget deposit',
      source: 'Etherscan label (eth-labels)',
    },
    '0x8c649c20a249135bdb7f0a6fe15d7e6033375994': {
      label: 'EIP-7702 account (TokenPocketSimple7702Account)',
      source: 'delegation in code',
    },
    '0x8f14f156149309361c0f6afef9145ab7c420fcf0': {
      label: 'Cobo deposit',
      source:
        'forwards 20 of its last 20 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0x9052e4013768189a419091293c366cdb27b559da': {
      label: 'Bybit deposit',
      source:
        'forwards 16 of its last 19 USDC transfers to Bybit: Opensea User (Etherscan label (eth-labels))',
    },
    '0x90f01cda8efb0568b6b4d93ab190193ac47ba469': {
      label: 'Roobet deposit',
      source:
        'forwards 94 of its last 94 USDC transfers to Roobet 3 (Etherscan label (eth-labels))',
    },
    '0x9628f74a3f49c92cc6b87603e8c7ec1644b34421': {
      label: 'TopUpV2',
      source: 'verified contract name (Etherscan)',
    },
    '0x9a4ebe49a963d3bc5f16639a0abff093ca0b040d': {
      label: 'GnosisSafeL2',
      source: 'verified contract name (Etherscan)',
    },
    '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48': {
      label: 'Circle: USDC Token',
      source: 'Etherscan label (eth-labels)',
    },
    '0xa2e511042c79058af047c4be3d66dc2680df2146': {
      label: 'EIP-7702 account (CaliburEntry)',
      source: 'delegation in code',
    },
    '0xa75598420ab6e00aeaa525f68d1336b097d24948': {
      label: 'Cobo deposit',
      source:
        'forwards 30 of its last 30 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0xaa59691120ca5f6f8f39441a5eced305c792f4a0': {
      label: 'Proxy',
      source: 'verified contract name (Etherscan)',
    },
    '0xabbde705208aaee63e582f567fc3a3cbefe56b95': {
      label: 'Cobo deposit',
      source:
        'forwards 22 of its last 22 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0xb40606297185041213dd79bf2125a9dbfd916420': {
      label: 'Cobo deposit',
      source:
        'forwards 47 of its last 47 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0xbadbb1de95b5f333623ebece7026932fa5039ee6': {
      label: 'EIP-7702 account (MetaMask: EIP-7702 Delegator)',
      source: 'delegation in code',
    },
    '0xbc5b3eb3a4821857435156c2a63fa1644e88a0c7': {
      label: 'Cobo deposit',
      source:
        'forwards 27 of its last 27 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0xbf329a7b2353112791f3f3039d376d5e2e40cdce': {
      label: 'Cobo deposit',
      source:
        'forwards 20 of its last 20 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0xbffc85e074a912de14a80f17914bd6292da8991c': {
      label: 'Cobo deposit',
      source:
        'forwards 24 of its last 24 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0xc5dd853a82ea72357c14fc43bc7f367714be6719': {
      label: 'EIP-7702 account (UniversalGaslessDelegate)',
      source: 'delegation in code',
    },
    '0xc61bc19600a62656787867f8d795974db881f4f8': {
      label: 'Cobo deposit',
      source:
        'forwards 31 of its last 31 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0xcc8059b688c31dd94164b9f1e33da4ba6e1264b0': {
      label: 'Nexus',
      source: 'verified contract name (Etherscan)',
    },
    '0xd861415f6703ab50ce101c7e6f6a80ada1fc2b1c': {
      label: 'buidlguidl-builders',
      source: 'Etherscan label (eth-labels)',
    },
    '0xdc60feb5d771bfacecc289d381abbd7d77d784e2': {
      label: 'Cobo deposit',
      source:
        'forwards 23 of its last 23 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0xdddee07b867b98eda59250c9ba2edde6ef1d42b4': {
      label: 'Cobo deposit',
      source:
        'forwards 22 of its last 22 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0xe2480f9e3dcb6e8356df3b7f0f40038f90606a85': {
      label: 'Cobo deposit',
      source:
        'forwards 20 of its last 20 USDC transfers to Cobo: Custody 1 (Etherscan label (eth-labels))',
    },
    '0xe2e311788e5201bc36fdd3090320c80ed0bf7fab': {
      label: 'Bitget deposit',
      source:
        'forwards 19 of its last 19 USDC transfers to Bitget 6 (Etherscan label (eth-labels))',
    },
    '0xe2e3a27311d4e29522b79de4191b67a7c1be5593': {
      label: 'Wirex deposit',
      source:
        'forwards 5 of its last 5 USDC transfers to Wirex 1 (Etherscan label (eth-labels))',
    },
    '0xed0799f6bcc13f3ad50cfce89945730c6172988f': {
      label: 'Stake.com deposit',
      source:
        'forwards 8 of its last 8 USDC transfers to Stake.com 9 (Etherscan label (eth-labels))',
    },
    '0xf8355f82b6434dabb8230aac77849e0fd2d6baee': {
      label: 'Gate.io deposit',
      source:
        'forwards 16 of its last 16 USDC transfers to Gate.io (Etherscan label (eth-labels))',
    },
    '0xf85bbf18543009e861fed02956f5bc400516985c': {
      label: 'EIP-7702 account (Simple7702Account)',
      source: 'delegation in code',
    },
    '0xfcec16c378e8cb65029093a3d5ab5a6a93b4b19a': {
      label: 'Forwarder',
      source: 'verified contract name (Etherscan)',
    },
    '0xff22cb582509f15abcc9a7d5957718ee02835d45': {
      label: 'Bybit deposit',
      source:
        'forwards 13 of its last 13 USDC transfers to Bybit: Opensea User (Etherscan label (eth-labels))',
    },
    '0xfff70bc720f6a22ae01afa91f35af6c62f34520e': {
      label: 'EIP-7702 account (UniversalGaslessDelegate)',
      source: 'delegation in code',
    },
  }
